/**
 * SAHAKARI SHRAMIK - COOPERATIVE DIGITAL SERVICE MARKETPLACE
 * Seed Data: 10 Categories, 20+ Verified Cooperative Workers, Societies, Initial State
 */

const COOP_CATEGORIES = [
  {
    id: "electrician",
    name: "Electrician",
    icon: "fa-bolt",
    shortDesc: "Wiring, switchboard, short circuits & home appliances",
    baseHourlyRate: 249,
    workerCount: 142,
    badgeColor: "#f59e0b"
  },
  {
    id: "plumber",
    name: "Plumber",
    icon: "fa-faucet-drip",
    shortDesc: "Leakage, water motor, sanitary ware & pipe fittings",
    baseHourlyRate: 220,
    workerCount: 118,
    badgeColor: "#0284c7"
  },
  {
    id: "carpenter",
    name: "Carpenter",
    icon: "fa-hammer",
    shortDesc: "Furniture repair, locks, modular fittings & wood polishing",
    baseHourlyRate: 299,
    workerCount: 96,
    badgeColor: "#b45309"
  },
  {
    id: "painter",
    name: "Painter",
    icon: "fa-paint-roller",
    shortDesc: "Interior & exterior wall painting, waterproof primer",
    baseHourlyRate: 279,
    workerCount: 104,
    badgeColor: "#ec4899"
  },
  {
    id: "domestic_helper",
    name: "Domestic Helper",
    icon: "fa-broom",
    shortDesc: "Kitchen support, housekeeping, dusting & utensil care",
    baseHourlyRate: 199,
    workerCount: 230,
    badgeColor: "#10b981"
  },
  {
    id: "caregiver",
    name: "Caregiver",
    icon: "fa-hand-holding-heart",
    shortDesc: "Elderly nursing, patient assistance, child care & post-op",
    baseHourlyRate: 349,
    workerCount: 88,
    badgeColor: "#8b5cf6"
  },
  {
    id: "driver",
    name: "Driver",
    icon: "fa-car",
    shortDesc: "Daily chauffeur, outstation trips & commercial vehicles",
    baseHourlyRate: 280,
    workerCount: 165,
    badgeColor: "#3b82f6"
  },
  {
    id: "gardener",
    name: "Gardener",
    icon: "fa-seedling",
    shortDesc: "Lawn trimming, terrace garden, plant nutrition & soil mix",
    baseHourlyRate: 210,
    workerCount: 74,
    badgeColor: "#15803d"
  },
  {
    id: "cleaner",
    name: "Cleaner",
    icon: "fa-soap",
    shortDesc: "Deep home sanitation, sofa/carpet shampooing, disinfection",
    baseHourlyRate: 260,
    workerCount: 180,
    badgeColor: "#06b6d4"
  },
  {
    id: "technician",
    name: "Technician",
    icon: "fa-screwdriver-wrench",
    shortDesc: "Air conditioner, refrigerator, microwave & RO water repair",
    baseHourlyRate: 349,
    workerCount: 135,
    badgeColor: "#6366f1"
  }
];

const COOP_SOCIETIES = [
  { id: "SOC-DEL-01", name: "Delhi Central Labour Cooperative Society Ltd." },
  { id: "SOC-DEL-02", name: "South Delhi Shramik Seva Cooperative Union" },
  { id: "SOC-MAH-01", name: "Mumbai Greater Labour Federation Co-op" },
  { id: "SOC-KAR-01", name: "Bengaluru Skilled Shramik Cooperative Union" },
  { id: "SOC-UP-01", name: "Noida-Ghaziabad Labour Welfare Co-op Society" },
  { id: "SOC-RAJ-01", name: "Jaipur Shramik Sahakari Samiti" }
];

const SEED_WORKERS = [
  {
    id: "wrk-101",
    name: "Ramesh Sharma",
    category: "electrician",
    rating: 4.9,
    reviewsCount: 128,
    experienceYears: 9,
    hourlyRate: 249,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34501",
    skills: ["Full Rewiring", "MCB Tripping", "Inverter Setup", "Short Circuit Repair"],
    bio: "ITI certified master electrician with 9 years of field expertise. Certified by National Skill Development Corporation (NSDC).",
    completedJobs: 342,
    avatarBg: "#1e3a8a",
    initials: "RS",
    city: "New Delhi"
  },
  {
    id: "wrk-102",
    name: "Sunil Verma",
    category: "plumber",
    rating: 4.8,
    reviewsCount: 94,
    experienceYears: 7,
    hourlyRate: 220,
    society: "South Delhi Shramik Seva #DL-22",
    societyId: "SOC-DEL-02",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34502",
    skills: ["Concealed Pipe Leaks", "T-Valve & Tap", "Water Motor Fitting", "Geyser Connection"],
    bio: "Cooperative member since 2018. Experienced in modern PVC, CPVC, and high-pressure bathroom fixtures.",
    completedJobs: 215,
    avatarBg: "#0369a1",
    initials: "SV",
    city: "New Delhi"
  },
  {
    id: "wrk-103",
    name: "Mohan Lal Mistri",
    category: "carpenter",
    rating: 4.9,
    reviewsCount: 110,
    experienceYears: 12,
    hourlyRate: 299,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34503",
    skills: ["Modular Wardrobes", "Door & Lock Repair", "French Polishing", "Custom Bed Assembly"],
    bio: "Senior artisan carpenter. Specializes in bespoke woodwork, quick lock repairs, and antique wood restoration.",
    completedJobs: 410,
    avatarBg: "#b45309",
    initials: "ML",
    city: "New Delhi"
  },
  {
    id: "wrk-104",
    name: "Kailash Chand",
    category: "painter",
    rating: 4.7,
    reviewsCount: 78,
    experienceYears: 8,
    hourlyRate: 279,
    society: "Noida-Ghaziabad Labour Co-op #UP-09",
    societyId: "SOC-UP-01",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34504",
    skills: ["Interior Emulsion", "Waterproofing", "Texture Painting", "Exterior Weatherproof"],
    bio: "Skilled cooperative painter trained in Asian Paints and Berger color application techniques.",
    completedJobs: 180,
    avatarBg: "#be185d",
    initials: "KC",
    city: "Noida"
  },
  {
    id: "wrk-105",
    name: "Sunita Devi",
    category: "domestic_helper",
    rating: 4.9,
    reviewsCount: 160,
    experienceYears: 6,
    hourlyRate: 199,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34505",
    skills: ["Deep Dusting", "Floor Mopping", "Utensil Cleaning", "Meal Preparation"],
    bio: "Punctual, background-verified household helper registered under the State Mahila Labour Cooperative.",
    completedJobs: 512,
    avatarBg: "#059669",
    initials: "SD",
    city: "New Delhi"
  },
  {
    id: "wrk-106",
    name: "Pooja Roy",
    category: "caregiver",
    rating: 5.0,
    reviewsCount: 86,
    experienceYears: 8,
    hourlyRate: 349,
    society: "South Delhi Shramik Seva #DL-22",
    societyId: "SOC-DEL-02",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34506",
    skills: ["Elderly Assistance", "Vitals Monitoring", "Medication Management", "Mobility Support"],
    bio: "Certified General Duty Assistant (GDA) by Healthcare Sector Skill Council. Specializes in compassionate geriatric care.",
    completedJobs: 198,
    avatarBg: "#7c3aed",
    initials: "PR",
    city: "New Delhi"
  },
  {
    id: "wrk-107",
    name: "Satish Yadav",
    category: "driver",
    rating: 4.8,
    reviewsCount: 142,
    experienceYears: 10,
    hourlyRate: 280,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34507",
    skills: ["Automatic & Manual", "Night Driving", "Outstation Routes", "VIP Protocol"],
    bio: "Commercial badge holder with 0 incident record in 10 years. Expert navigation across NCR and highways.",
    completedJobs: 620,
    avatarBg: "#2563eb",
    initials: "SY",
    city: "Gurugram"
  },
  {
    id: "wrk-108",
    name: "Ram Kripal",
    category: "gardener",
    rating: 4.8,
    reviewsCount: 65,
    experienceYears: 11,
    hourlyRate: 210,
    society: "South Delhi Shramik Seva #DL-22",
    societyId: "SOC-DEL-02",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34508",
    skills: ["Lawn Mowing", "Bonsai & Pruning", "Organic Compost", "Terrace Gardening"],
    bio: "Passionate horticulturist cooperative member. Expert in seasonal flowering plants and pest eradication.",
    completedJobs: 175,
    avatarBg: "#15803d",
    initials: "RK",
    city: "New Delhi"
  },
  {
    id: "wrk-109",
    name: "Imran Khan",
    category: "cleaner",
    rating: 4.9,
    reviewsCount: 114,
    experienceYears: 5,
    hourlyRate: 260,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34509",
    skills: ["Sofa Shampooing", "Bathroom Descaling", "Kitchen Degreasing", "Balcony Wash"],
    bio: "Carries commercial grade dry vacuum and eco-friendly Taski cleaning chemicals.",
    completedJobs: 290,
    avatarBg: "#0891b2",
    initials: "IK",
    city: "New Delhi"
  },
  {
    id: "wrk-110",
    name: "Amitabh Sen",
    category: "technician",
    rating: 4.9,
    reviewsCount: 156,
    experienceYears: 9,
    hourlyRate: 349,
    society: "South Delhi Shramik Seva #DL-22",
    societyId: "SOC-DEL-02",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34510",
    skills: ["AC Gas Refill", "Split AC Deep Jet Service", "Inverter PCB Repair", "Washing Machine Motor"],
    bio: "Authorized HVAC technician. Cooperative registered for fair, transparent spare part pricing.",
    completedJobs: 430,
    avatarBg: "#4f46e5",
    initials: "AS",
    city: "New Delhi"
  },
  {
    id: "wrk-111",
    name: "Dinesh Kumar",
    category: "electrician",
    rating: 4.7,
    reviewsCount: 68,
    experienceYears: 5,
    hourlyRate: 249,
    society: "Noida-Ghaziabad Labour Co-op #UP-09",
    societyId: "SOC-UP-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34511",
    skills: ["LED Chandelier", "Earthing Check", "Ceiling Fan", "Switchboard Wiring"],
    bio: "Fast response emergency electrician covering East Delhi and Noida Sector 15-62.",
    completedJobs: 160,
    avatarBg: "#d97706",
    initials: "DK",
    city: "Noida"
  },
  {
    id: "wrk-112",
    name: "Manoj Rawat",
    category: "plumber",
    rating: 4.8,
    reviewsCount: 82,
    experienceYears: 6,
    hourlyRate: 220,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34512",
    skills: ["Overhead Tank Cleaning", "Submersible Motor", "Kitchen Sink Choke", "Shower Fitting"],
    bio: "Reliable plumber with specialized tools for quick leak detection without wall damage.",
    completedJobs: 195,
    avatarBg: "#0284c7",
    initials: "MR",
    city: "New Delhi"
  },
  {
    id: "wrk-113",
    name: "Harishankar Pandey",
    category: "carpenter",
    rating: 4.6,
    reviewsCount: 54,
    experienceYears: 8,
    hourlyRate: 299,
    society: "South Delhi Shramik Seva #DL-22",
    societyId: "SOC-DEL-02",
    verified: true,
    emergencyAvailable: false,
    phone: "+91 98112 34513",
    skills: ["Drawer Channels", "Curtain Rods", "Wooden Partitions", "Sofa Frame Repair"],
    bio: "Expert in home fittings, sliding door alignment, and customized wooden fixtures.",
    completedJobs: 140,
    avatarBg: "#92400e",
    initials: "HP",
    city: "New Delhi"
  },
  {
    id: "wrk-114",
    name: "Anita Mukherjee",
    category: "caregiver",
    rating: 4.9,
    reviewsCount: 72,
    experienceYears: 7,
    hourlyRate: 349,
    society: "Delhi Central Labour Co-op #DL-14",
    societyId: "SOC-DEL-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34514",
    skills: ["Bedridden Patient Care", "Insulin Admin", "Physiotherapy Assist", "Dementia Care"],
    bio: "Compassionate, patient caregiver with hospital bedside assistance experience.",
    completedJobs: 180,
    avatarBg: "#6d28d9",
    initials: "AM",
    city: "New Delhi"
  },
  {
    id: "wrk-115",
    name: "Vikram Chauhan",
    category: "technician",
    rating: 4.8,
    reviewsCount: 88,
    experienceYears: 6,
    hourlyRate: 349,
    society: "Noida-Ghaziabad Labour Co-op #UP-09",
    societyId: "SOC-UP-01",
    verified: true,
    emergencyAvailable: true,
    phone: "+91 98112 34515",
    skills: ["RO Membrane Change", "Refrigerator Compressor", "Microwave Magnetron", "Front Load Washer"],
    bio: "Home appliance technician equipped with multi-meter and genuine certified parts.",
    completedJobs: 240,
    avatarBg: "#4338ca",
    initials: "VC",
    city: "Noida"
  }
];

const SEED_BOOKINGS = [
  {
    id: "SHK-2026-8921",
    serviceCategory: "electrician",
    serviceName: "Emergency MCB & Circuit Fix",
    workerId: "wrk-101",
    workerName: "Ramesh Sharma",
    workerPhone: "+91 98112 34501",
    customerId: "cust-01",
    customerName: "Rajesh Kumar",
    customerPhone: "+91 98765 43210",
    serviceAddress: "Flat 402, Shivalik Apartments, Sector 14, New Delhi - 110025",
    date: "2026-09-04",
    timeSlot: "10:00 AM - 12:00 PM",
    isEmergency: true,
    status: "accepted", // pending, accepted, in-progress, completed, cancelled
    baseFare: 249,
    welfareFund: 12,
    totalFare: 261,
    notes: "Main circuit breaker is tripping repeatedly since heavy rain.",
    createdAt: "2026-09-03T14:30:00Z",
    otp: "5429"
  },
  {
    id: "SHK-2026-8740",
    serviceCategory: "plumber",
    serviceName: "Bathroom Shower & Tap Valve Replacement",
    workerId: "wrk-102",
    workerName: "Sunil Verma",
    workerPhone: "+91 98112 34502",
    customerId: "cust-01",
    customerName: "Rajesh Kumar",
    customerPhone: "+91 98765 43210",
    serviceAddress: "Flat 402, Shivalik Apartments, Sector 14, New Delhi - 110025",
    date: "2026-09-02",
    timeSlot: "02:00 PM - 04:00 PM",
    isEmergency: false,
    status: "completed",
    baseFare: 440,
    welfareFund: 22,
    totalFare: 462,
    notes: "Leakage fixed cleanly. Installed new ceramic disk valve.",
    createdAt: "2026-09-02T09:15:00Z",
    rating: 5,
    review: "Prompt, honest rate, no unnecessary extra parts recommended. Great cooperative service!"
  }
];
